# AzusaMute Configuration

allow-op: true

messages:
  broadcast_mute: "§e{player} §fgets a mute penalty for §c{time}"
  player_mute: "You have been mute for §c{time} §fby §b{punisher}"
  mute_ended: "You are free from the §emute penalty"
  already_muted: "§cThe player is already on mute"
  not_muted: "§cThe player is not on mute"
  unmute_success: "You are free from the §emute penalty"
  broadcast_mute_all: "§cAll players on the server are mute"
  broadcast_unmute_all: "§eAll players on the server are free from mute"
  already_muted_all: "§cThe server is already on mute"
  not_muted_all: "§cThe server is not in mute state"
  mute_check: "§e{player} §fwas mute within §c{time} §fby §b{punisher}"
  mute_all: "§cYou cannot send messages because the server is on mute"
  player_muted: "You cannot send messages because you are on mute for §c{time}"
  op_mute: "§cOP players cannot be muted"